connection: 
  host: jdbc:mysql://localhost:3306/
  schema: database
  username: user
  password: password
  
#
# Permissions 
# To allow players to access certain commands themselves
# add the corresponding minecraft.command.<command> permission
#
# - > http://wiki.bukkit.org/CraftBukkit_Commands
#
# [ Standart MC: http://minecraft.gamepedia.com/Commands ]
