name: CommandPlot
description: Fixes Commandblocks for PlotSquared [ALPHA!]
author: richbar

main: richbar.com.github.commandplot.CPlugin

depend: [PlotSquared]

version: 0.5.0
#        ALPHA

commands:
  commandblock:
    permission: plots.commandblock
    aliases: cb
    description: Gives you a commandblock.
    permission-message: "You are lacking the permission node 'plots.commandblock'"
  commandblockmode:
    permission: plots.commandblock.changemode
    aliases: cbm
    description: Allows you to edit Commandblocks.
    permission-message: "You are lacking the permission node 'plots.commandblock.changemode'"
  commandplot:
    permission: plots.commandblock.admin
    description: Admin options for CommandPlot
    permission-message: "You are lacking the permission node 'plots.commandblock.admin'"
    
permissions:
  plots.commandblock:
    default: true
  plots.commandblock.changemode:
    default: true
  plots.commandblock.admin:
    default: false