name: CommandPlot
description: Fixes Commandblocks for PlotSquared [ALPHA!]
author: richbar

main: richbar.com.github.commandplot.CPlugin

depend: [PlotSquared]

version: 0.4.5
#        ALPHA

commands:
  commandblock:
    permission: plots.commandblock
    aliases: cb
    description: Gives you a commandblock.
    permission-message: "You are lacking the permission node 'plots.commandblock'"
  commandblockmode:
    permission: plots.commandblock.changemode
    aliases: cbm
    description: Allows you to edit Commandblocks.
    permission-message: "You are lacking the permission node 'plots.commandblock.changemode'"
  transmit:
    permission: plots.commandblock.transmit
    description: Commandblock Command...
    permission-message: "You are lacking the permission node 'plots.commandblock.transmit'"
  receive:
    permission: plots.commandblock.receive
    description: Commandblock Command...
    permission-message: "You are lacking the permission node 'plots.commandblock.receive'"
    
permissions:
  plots.commandblock:
    default: true
  plots.commandblock.changemode:
    default: true
  plots.commandblock.transmit:
    default: false
  plots.commandblock.receive:
    default: false